-- Geração X — schema espelhando o questionário real (Google Forms).
-- ATENÇÃO: recria a tabela do zero (apaga todos os dados).

drop table if exists public.responses cascade;

create table public.responses (
  id bigint generated by default as identity primary key,
  submitted_at timestamptz not null default now(),
  source text not null default 'dashboard' check (source in ('google_forms', 'dashboard')),

  -- Perfil
  age_band text not null,
  region text,
  employment_status text,
  household_income text,

  -- Mobilidade, território e acessibilidade
  car_dependency_factors text[] not null default '{}',
  daily_commute_time text,
  walking_willingness text,
  walk_access text[] not null default '{}',

  -- Relação atual com veículos
  vehicle_relationship text,
  vehicle_acquisition text,
  transport_modes text[] not null default '{}',
  no_car_reason text,
  car_access_triggers text[] not null default '{}',
  future_vehicle_stance text,
  vehicle_type text,
  vehicle_powertrain text,
  vehicle_year_range text,
  vehicle_sharing text,
  monthly_vehicle_cost text,
  weekly_vehicle_use text,
  routine_depends_on_car text,          -- Likert: "Minha rotina depende de ter acesso a um carro"
  can_use_alternatives text,            -- Likert: "Consigo realizar meus deslocamentos com alternativas"
  car_required_activities text[] not null default '{}',

  -- Alternativas e propensão futura
  alternative_modes text[] not null default '{}',
  alternative_transport_factors text[] not null default '{}',
  mobility_intentions jsonb not null default '{}'::jsonb,   -- {alternativa: probabilidade}
  ownership_importance smallint check (ownership_importance between 1 and 5),

  -- Financiamento e confiança
  financing_factors jsonb not null default '{}'::jsonb,     -- {fator: relevância}
  compatible_monthly_payment text,
  acceptable_down_payment text,
  trust_drivers jsonb not null default '{}'::jsonb,         -- {fator: relevância}
  financing_journey jsonb not null default '{}'::jsonb,     -- {etapa: formato preferido}
  digital_channels text[] not null default '{}',

  -- Instituições e benefícios
  institutions jsonb not null default '{}'::jsonb,          -- {instituição: [relações]}
  benefits jsonb not null default '{}'::jsonb,              -- {benefício: tipo de solução}

  -- Veículos elétricos
  ev_access_options text[] not null default '{}',
  ev_attitudes jsonb not null default '{}'::jsonb,          -- {afirmação: concordância}
  home_charging_status text,
  ev_solutions text[] not null default '{}',

  -- Indicadores calculados pelo trigger (ver public.compute_response_indicators)
  ida_score numeric(5,2) check (ida_score between 0 and 100),
  ida_band text check (ida_band in ('Baixa', 'Média', 'Alta')),
  financing_propensity numeric(5,2) check (financing_propensity between 0 and 100),
  ev_readiness_score numeric(5,2) check (ev_readiness_score between 0 and 100),
  ev_readiness_band text check (ev_readiness_band in ('Baixa', 'Média', 'Alta')),

  -- Governança
  is_eligible boolean not null default false,
  potential_duplicate boolean not null default false,
  created_at timestamptz not null default now()
);

create index responses_region_idx on public.responses (region);
create index responses_age_band_idx on public.responses (age_band);
create index responses_submitted_at_idx on public.responses (submitted_at desc);

-- Escalas usadas nos indicadores (0–100). Textos fora da escala retornam null e ficam fora do cálculo.
create or replace function public.score_agreement(answer text) returns numeric language sql immutable as $$
  select case lower(trim(answer))
    when 'discordo totalmente' then 0 when 'discordo' then 25 when 'discordo parcialmente' then 25
    when 'neutro' then 50 when 'concordo' then 75 when 'concordo parcialmente' then 75
    when 'concordo totalmente' then 100 end
$$;

create or replace function public.score_probability(answer text) returns numeric language sql immutable as $$
  select case answer
    when 'Improvável' then 0 when 'Pouco provável' then 25 when 'Possivelmente' then 50
    when 'Provável' then 75 when 'Muito provável' then 100 end
$$;

create or replace function public.band_0_100(score numeric) returns text language sql immutable as $$
  select case when score is null then null when score < 34 then 'Baixa' when score < 67 then 'Média' else 'Alta' end
$$;

create or replace function public.compute_response_indicators() returns trigger language plpgsql as $$
declare
  components numeric[];
  transit_access int;
begin
  -- Elegibilidade: 45–61 anos e residente no município de São Paulo
  new.is_eligible := new.age_band in ('45 a 49 anos', '50 a 54 anos', '55 a 61 anos')
    and new.region like 'Zona %';

  -- IDA — média dos componentes disponíveis (mínimo 3):
  --   dependência declarada, alternativas (invertido), dias de uso, disposição a caminhar (invertido),
  --   acesso a pé a transporte coletivo (invertido)
  if cardinality(new.walk_access) > 0 and not new.walk_access <@ array['Não sei informar'] then
    select count(*) into transit_access from unnest(new.walk_access) as option
    where option in ('Ponto de ônibus', 'Terminal ou corredor de ônibus', 'Estação de metrô', 'Estação de trem/CPTM');
  end if;
  components := array_remove(array[
    public.score_agreement(new.routine_depends_on_car),
    100 - public.score_agreement(new.can_use_alternatives),
    case new.weekly_vehicle_use when 'Nenhum dia' then 0 when '1 a 2 dias' then 25 when '3 a 4 dias' then 50
      when '5 a 6 dias' then 75 when 'Todos os dias' then 100 end,
    case new.walking_willingness when 'Acima de 30 minutos' then 0 when 'De 20 a 30 minutos' then 25
      when 'De 10 a 20 minutos' then 50 when 'Até 10 minutos' then 75 when 'Não estou disposto(a) a caminhar' then 100 end,
    case when transit_access is null then null else greatest(0, 100 - transit_access * 100.0 / 3) end
  ], null);
  new.ida_score := case when cardinality(components) >= 3
    then round((select avg(value) from unnest(components) as value), 2) end;
  new.ida_band := public.band_0_100(new.ida_score);

  -- Propensão a financiar = probabilidade declarada de "Financiar um carro" nos próximos 3 anos
  new.financing_propensity := public.score_probability(new.mobility_intentions ->> 'Financiar um carro');

  -- Readiness EV — média de viabilidade de recarga residencial e disposição a financiar um elétrico
  components := array_remove(array[
    case
      when new.home_charging_status is null then null
      when new.home_charging_status = 'Já existe carregador ou estrutura adequada' then 100
      when new.home_charging_status = 'Tenho vaga e acredito que seria possível instalar um carregador' then 75
      when new.home_charging_status = 'Tenho vaga, mas não sei se seria possível instalar' then 50
      when new.home_charging_status = 'Tenho vaga, mas acredito que não seria possível instalar' then 25
      else 0 end,
    public.score_agreement(new.ev_attitudes ->> 'Eu consideraria financiar um carro elétrico se as condições financeiras fossem atrativas.')
  ], null);
  new.ev_readiness_score := case when cardinality(components) = 2
    then round((select avg(value) from unnest(components) as value), 2) end;
  new.ev_readiness_band := public.band_0_100(new.ev_readiness_score);

  return new;
end;
$$;

create trigger responses_compute_indicators
before insert or update on public.responses
for each row execute function public.compute_response_indicators();

-- RLS: leitura pública apenas de respostas elegíveis; inserção pelo formulário do painel.
alter table public.responses enable row level security;

create policy "Public can read eligible responses"
  on public.responses for select to anon, authenticated
  using (is_eligible = true);

create policy "Public can submit responses from dashboard"
  on public.responses for insert to anon, authenticated
  with check (source = 'dashboard');

-- Contagem total (inclui fora do perfil) para o monitoramento da coleta, sem expor as linhas.
create or replace function public.collection_summary()
returns table (total bigint, eligible bigint, ineligible bigint)
language sql stable security definer set search_path = public as $$
  select count(*), count(*) filter (where is_eligible), count(*) filter (where not is_eligible) from public.responses
$$;
grant execute on function public.collection_summary() to anon, authenticated;

-- Atualizações em tempo real no painel
do $$ begin
  alter publication supabase_realtime add table public.responses;
exception when others then null;
end $$;
