create table if not exists public.responses (
  id bigint generated by default as identity primary key,
  respondent_name text not null,
  age smallint not null check (age between 45 and 61),
  city text not null default 'São Paulo',
  region text not null,
  household_income text,
  employment_status text,

  -- Relação atual com veículos
  vehicle_relationship text,
  vehicle_type text,
  vehicle_powertrain text,
  vehicle_year_range text,
  vehicle_sharing text,
  weekly_vehicle_use text,
  perceived_monthly_vehicle_cost text,
  renewal_potential text,

  -- Mobilidade, território e acessibilidade
  daily_commute_time text,
  walking_willingness text,
  commute_time_by_region text,
  nearby_services text[] default '{}',
  car_dependency_factors text[] default '{}',
  alternative_modes text[] default '{}',
  alternative_transport_factors text[] default '{}',

  -- Índice de Dependência do Automóvel (calculado na Base tratada)
  ida_score numeric(5,2) check (ida_score between 0 and 100),
  ida_band text check (ida_band in ('Baixa', 'Média', 'Alta')),

  -- Propensão futura a soluções de mobilidade
  mobility_propensity numeric(5,2) check (mobility_propensity between 0 and 100),
  propensity_car_purchase numeric(5,2),
  propensity_subscription numeric(5,2),
  propensity_rental numeric(5,2),
  propensity_shared_mobility numeric(5,2),
  propensity_public_transport numeric(5,2),

  -- Financiamento e confiança
  financing_factors text[] default '{}',
  compatible_monthly_payment text,
  acceptable_down_payment text,
  financing_propensity numeric(3,2),
  trust_drivers text[] default '{}',
  preferred_financing_channel text,
  financing_journey_preferences jsonb not null default '{}'::jsonb,
  digital_channels text[] default '{}',

  -- Relacionamento com instituições e benefícios
  financial_institutions text[] default '{}',
  santander_segment text,
  valued_benefits text[] default '{}',
  preferred_solution_type text,

  -- Veículos elétricos / Readiness EV
  ev_interest text,
  ev_readiness_score numeric(5,2) check (ev_readiness_score between 0 and 100),
  ev_readiness_band text,
  ev_access_options text[] default '{}',
  ev_motivators text[] default '{}',
  ev_barriers text[] default '{}',
  home_charging_status text,
  ev_financing_interest text,
  ev_subscription_interest text,
  ev_rental_interest text,

  -- Governança e qualidade da coleta
  is_eligible boolean not null default true,
  potential_duplicate boolean not null default false,
  data_quality_notes text,
  source_response_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists responses_region_idx on public.responses (region);
create index if not exists responses_age_idx on public.responses (age);
create index if not exists responses_income_idx on public.responses (household_income);
create index if not exists responses_ida_band_idx on public.responses (ida_band);
create index if not exists responses_created_at_idx on public.responses (created_at desc);

alter table public.responses enable row level security;

drop policy if exists "Public can submit eligible responses" on public.responses;
create policy "Public can submit eligible responses"
  on public.responses for insert
  to anon, authenticated
  with check (age between 45 and 61 and city = 'São Paulo' and is_eligible = true);

drop policy if exists "Public can read eligible responses" on public.responses;
create policy "Public can read eligible responses"
  on public.responses for select
  to anon, authenticated
  using (is_eligible = true);

create or replace function public.set_responses_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists responses_updated_at on public.responses;
create trigger responses_updated_at
before update on public.responses
for each row execute function public.set_responses_updated_at();
