insert into public.responses (
  respondent_name, age, region, household_income, employment_status,
  vehicle_relationship, vehicle_type, vehicle_powertrain, vehicle_year_range,
  weekly_vehicle_use, daily_commute_time, walking_willingness,
  nearby_services, car_dependency_factors, alternative_modes,
  ida_score, ida_band, mobility_propensity,
  compatible_monthly_payment, acceptable_down_payment, financing_propensity,
  preferred_financing_channel, financial_institutions, valued_benefits,
  preferred_solution_type, ev_interest, ev_readiness_score, ev_readiness_band,
  ev_access_options, ev_motivators, ev_barriers, home_charging_status,
  is_eligible, source_response_id
)
select
  'Respondente exemplo ' || lpad(series::text, 2, '0'),
  45 + (series % 17),
  (array['Centro expandido', 'Zona leste', 'Zona sul', 'Zona norte', 'Zona oeste'])[1 + (series % 5)],
  (array['Até R$ 4.000', 'R$ 4.001 a R$ 10.000', 'R$ 10.001 a R$ 20.000', 'Acima de R$ 20.000'])[1 + (series % 4)],
  (array['Trabalho em período integral', 'Autônomo(a)', 'Aposentado(a)', 'Trabalho em período parcial'])[1 + (series % 4)],
  (array['Tenho e uso regularmente', 'Tenho, mas uso pouco', 'Não tenho, mas uso de terceiros'])[1 + (series % 3)],
  (array['SUV', 'Hatch', 'Sedan', 'Não se aplica'])[1 + (series % 4)],
  (array['Flex', 'Elétrico', 'Híbrido', 'Flex'])[1 + (series % 4)],
  (array['2015–2019', '2020–2024', 'Antes de 2015', '2020–2024'])[1 + (series % 4)],
  (array['1–2 dias', '3–4 dias', '5–7 dias'])[1 + (series % 3)],
  (array['Até 30 minutos', '31 a 60 minutos', '61 a 120 minutos', 'Mais de 120 minutos'])[1 + (series % 4)],
  (array['Sempre', 'Frequentemente', 'Às vezes', 'Raramente'])[1 + (series % 4)],
  array['Ônibus', 'Metrô', 'Comércio', 'Ciclovia'],
  array[(array['Tempo de deslocamento', 'Baixa oferta de transporte', 'Custo', 'Conforto e segurança'])[1 + (series % 4)]],
  array[(array['Transporte público', 'Aplicativo', 'Bicicleta', 'Carona'])[1 + (series % 4)]],
  round((42 + (series % 16) * 3.7)::numeric, 2),
  case when series % 3 = 0 then 'Baixa' when series % 3 = 1 then 'Média' else 'Alta' end,
  round((48 + (series % 22) * 2.4)::numeric, 2),
  (array['Até R$ 1.000', 'R$ 1.001 a R$ 2.000', 'R$ 2.001 a R$ 3.500'])[1 + (series % 3)],
  (array['Até 10%', '11% a 20%', '21% a 30%'])[1 + (series % 3)],
  round((0.48 + series * 0.035)::numeric, 2),
  (array['App', 'Agência', 'WhatsApp', 'Site'])[1 + (series % 4)],
  array['Santander', 'Itaú'],
  array['Taxa competitiva', 'Transparência', 'Flexibilidade'],
  (array['Financiamento', 'Aluguel/assinatura', 'Ambos'])[1 + (series % 3)],
  (array['Sim, com certeza', 'Talvez', 'Ainda não'])[1 + (series % 3)],
  round((30 + (series % 18) * 4.1)::numeric, 2),
  case when series % 3 = 0 then 'Alta' when series % 3 = 1 then 'Média' else 'Baixa' end,
  array['Financiamento', 'Assinatura'],
  array['Economia no uso', 'Sustentabilidade'],
  array['Recarga residencial', 'Preço inicial'],
  (array['Tenho vaga com recarga', 'Tenho vaga sem recarga', 'Não tenho vaga'])[1 + (series % 3)],
  true,
  'SEED-' || lpad(series::text, 3, '0')
from generate_series(1, 24) as generated(series)
on conflict do nothing;
